run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - misspell
    - unconvert
    - unparam
    - gocritic

linters-settings:
  errcheck:
    check-type-assertions: true
  gocritic:
    enabled-tags:
      - diagnostic
      - performance
  goimports:
    local-prefixes: github.com/kris-hansen/feelgoodbot
  misspell:
    locale: US

issues:
  exclude-rules:
    # Allow unused parameters in test files
    - path: _test\.go
      linters:
        - unparam
    # Allow exec.Command without checking errors in some cases
    - path: internal/alerts/
      text: "Error return value of .* is not checked"
      linters:
        - errcheck
