version: "2"

run:
  timeout: 5m
  modules-download-mode: readonly

formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/kris-hansen/feelgoodbot

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - unconvert
    - unparam
    - gocritic
  settings:
    errcheck:
      check-type-assertions: true
    gocritic:
      enabled-tags:
        - diagnostic
      disabled-checks:
        - ifElseChain
        - appendAssign
        - filepathJoin
    misspell:
      locale: US
  exclusions:
    presets:
      - std-error-handling
      - common-false-positives
    rules:
      - path: _test\.go
        linters:
          - unparam
      - path: internal/alerts/
        text: "Error return value of .* is not checked"
        linters:
          - errcheck
      # Disable ifElseChain - sometimes clearer than switch
      - text: "ifElseChain"
        linters:
          - gocritic
      # WriteString with Sprintf is fine for readability
      - text: "QF1012"
        linters:
          - staticcheck
      # Tagged switch suggestions - sometimes if-else is clearer
      - text: "QF1003"
        linters:
          - staticcheck
      # unnecessary conversion is sometimes intentional
      - text: "unnecessary conversion"
        linters:
          - unconvert
